language: java
jdk: openjdk11

cache:
  directories:
  - $HOME/.m2

before_script:
- mysql -e 'create database peopleandtasks'
#- mysql -c 'create user "user"; grant all privileges on database peopleandtasks to "user"' -U mysql

branches:
  only:
  - master

services:
  - mysql
