language: java
jdk: openjdk11

cache:
  directories:
  - $HOME/.m2

before_script:
  - mysql -c 'create database peopleandtask' -U mysql
  - mysql -c 'create user "root"; grant all privileges on database peopleandtask to "root"' -U mysql

branches:
  only:
  - master

services:
  - mysql
