language: java
jdk: openjdk11

cache:
  directories:
  - $HOME/.m2

branches:
  only:
  - master

services:
  - mysql

before_script:
  - mysql -u root -e "SET character_set_client='utf8';"
  - mysql -u root -e "SET character_set_connection='utf8';"
  - mysql -u root -e "SET character_set_results='utf8';"
  - mysql -u root -e "CREATE DATABASE peopleandtasks;"
  - mysql -u root -e "CREATE USER 'makler'@'localhost' IDENTIFIED BY 'makler';"
  - mysql -u root -e "GRANT ALL ON peopleandtasks.* TO 'makler'@'localhost';"
