language: java
jdk: openjdk11

cache:
  directories:
  - $HOME/.m2

branches:
  only:
  - master

services:
  - mysql

install:
  - mysql -u root -e 'CREATE USER IF NOT EXISTS travis@localhost; GRANT ALL ON *.* TO travis@localhost;'
