language: java
jdk: openjdk11

cache:
  directories:
  - $HOME/.m2

branches:
  only:
  - master

services:
  - mysql

before_script:
  - mysql -u root -e "SET NAMES utf8;"
  - mysql -u root -e "SET CHARACTER SET utf8;"
  - mysql -u root -e "SET COLLATION_CONNECTION='utf8_general_ci';"
  - mysql -u root -e "CREATE DATABASE peopleandtasks CHARACTER SET utf8 COLLATE utf8_general_ci;"
  - mysql -u root -e "CREATE USER 'makler'@'localhost' IDENTIFIED BY 'makler';"
  - mysql -u root -e "GRANT ALL ON peopleandtasks.* TO 'makler'@'localhost';"

before_install:
  - mysql -u root -e "SET NAMES utf8;"
  - mysql -u root -e "SET CHARACTER SET utf8;"
  - mysql -u root -e "SET COLLATION_CONNECTION='utf8_general_ci';"
  - mysql -u root -e "CREATE DATABASE peopleandtasks CHARACTER SET utf8 COLLATE utf8_general_ci;"
  - mysql -u root -e "CREATE USER 'makler'@'localhost' IDENTIFIED BY 'makler';"
  - mysql -u root -e "GRANT ALL ON peopleandtasks.* TO 'makler'@'localhost';"
